# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_linear_interpolation.ui'
#
# Created: Wed Feb 18 18:00:19 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LinearInterpolationDialogBase(object):
    def setupUi(self, LinearInterpolationDialogBase):
        LinearInterpolationDialogBase.setObjectName(_fromUtf8("LinearInterpolationDialogBase"))
        LinearInterpolationDialogBase.resize(526, 394)
        self.button_box = QtGui.QDialogButtonBox(LinearInterpolationDialogBase)
        self.button_box.setGeometry(QtCore.QRect(20, 360, 341, 41))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.comboBox = QtGui.QComboBox(LinearInterpolationDialogBase)
        self.comboBox.setGeometry(QtCore.QRect(130, 20, 171, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox_2 = QtGui.QComboBox(LinearInterpolationDialogBase)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 50, 171, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_3 = QtGui.QComboBox(LinearInterpolationDialogBase)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 80, 171, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_4 = QtGui.QComboBox(LinearInterpolationDialogBase)
        self.comboBox_4.setGeometry(QtCore.QRect(180, 110, 171, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_5 = QtGui.QComboBox(LinearInterpolationDialogBase)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 140, 171, 22))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.lineEdit = QtGui.QLineEdit(LinearInterpolationDialogBase)
        self.lineEdit.setGeometry(QtCore.QRect(110, 200, 71, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(LinearInterpolationDialogBase)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 200, 71, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(LinearInterpolationDialogBase)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 230, 71, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(LinearInterpolationDialogBase)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 230, 71, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.checkBox = QtGui.QCheckBox(LinearInterpolationDialogBase)
        self.checkBox.setGeometry(QtCore.QRect(140, 290, 331, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_6.setGeometry(QtCore.QRect(10, 200, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_5 = QtGui.QLineEdit(LinearInterpolationDialogBase)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 260, 71, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_7 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_7.setGeometry(QtCore.QRect(200, 200, 91, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_9.setGeometry(QtCore.QRect(200, 230, 91, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_10.setGeometry(QtCore.QRect(10, 260, 91, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.checkBox_2 = QtGui.QCheckBox(LinearInterpolationDialogBase)
        self.checkBox_2.setGeometry(QtCore.QRect(140, 310, 381, 17))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.label_11 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_11.setGeometry(QtCore.QRect(200, 260, 111, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_6 = QtGui.QLineEdit(LinearInterpolationDialogBase)
        self.lineEdit_6.setGeometry(QtCore.QRect(310, 260, 71, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.comboBox_6 = QtGui.QComboBox(LinearInterpolationDialogBase)
        self.comboBox_6.setEnabled(False)
        self.comboBox_6.setGeometry(QtCore.QRect(180, 170, 171, 22))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.label_12 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_12.setGeometry(QtCore.QRect(10, 170, 151, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.checkBox_3 = QtGui.QCheckBox(LinearInterpolationDialogBase)
        self.checkBox_3.setGeometry(QtCore.QRect(160, 170, 16, 17))
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.comboBox_7 = QtGui.QComboBox(LinearInterpolationDialogBase)
        self.comboBox_7.setGeometry(QtCore.QRect(320, 20, 171, 22))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_8 = QtGui.QComboBox(LinearInterpolationDialogBase)
        self.comboBox_8.setGeometry(QtCore.QRect(320, 50, 171, 22))
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.label_13 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_13.setGeometry(QtCore.QRect(160, 0, 91, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_14.setGeometry(QtCore.QRect(360, 0, 91, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(LinearInterpolationDialogBase)
        self.label_15.setGeometry(QtCore.QRect(400, 200, 51, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_7 = QtGui.QLineEdit(LinearInterpolationDialogBase)
        self.lineEdit_7.setGeometry(QtCore.QRect(450, 200, 71, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.pushButton = QtGui.QPushButton(LinearInterpolationDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(4, 340, 141, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_8 = QtGui.QLineEdit(LinearInterpolationDialogBase)
        self.lineEdit_8.setGeometry(QtCore.QRect(150, 340, 351, 20))
        self.lineEdit_8.setText(_fromUtf8(""))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))

        self.retranslateUi(LinearInterpolationDialogBase)
        self.comboBox_4.setCurrentIndex(-1)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), LinearInterpolationDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), LinearInterpolationDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(LinearInterpolationDialogBase)
        LinearInterpolationDialogBase.setTabOrder(self.comboBox, self.comboBox_2)
        LinearInterpolationDialogBase.setTabOrder(self.comboBox_2, self.comboBox_3)
        LinearInterpolationDialogBase.setTabOrder(self.comboBox_3, self.comboBox_4)
        LinearInterpolationDialogBase.setTabOrder(self.comboBox_4, self.comboBox_5)
        LinearInterpolationDialogBase.setTabOrder(self.comboBox_5, self.checkBox_3)
        LinearInterpolationDialogBase.setTabOrder(self.checkBox_3, self.comboBox_6)
        LinearInterpolationDialogBase.setTabOrder(self.comboBox_6, self.lineEdit)
        LinearInterpolationDialogBase.setTabOrder(self.lineEdit, self.lineEdit_2)
        LinearInterpolationDialogBase.setTabOrder(self.lineEdit_2, self.lineEdit_7)
        LinearInterpolationDialogBase.setTabOrder(self.lineEdit_7, self.lineEdit_3)
        LinearInterpolationDialogBase.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        LinearInterpolationDialogBase.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        LinearInterpolationDialogBase.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        LinearInterpolationDialogBase.setTabOrder(self.lineEdit_6, self.checkBox)
        LinearInterpolationDialogBase.setTabOrder(self.checkBox, self.checkBox_2)
        LinearInterpolationDialogBase.setTabOrder(self.checkBox_2, self.pushButton)
        LinearInterpolationDialogBase.setTabOrder(self.pushButton, self.lineEdit_8)
        LinearInterpolationDialogBase.setTabOrder(self.lineEdit_8, self.comboBox_7)
        LinearInterpolationDialogBase.setTabOrder(self.comboBox_7, self.comboBox_8)

    def retranslateUi(self, LinearInterpolationDialogBase):
        LinearInterpolationDialogBase.setWindowTitle(_translate("LinearInterpolationDialogBase", "Linear Interpolation", None))
        self.lineEdit.setText(_translate("LinearInterpolationDialogBase", "200", None))
        self.lineEdit_2.setText(_translate("LinearInterpolationDialogBase", "200", None))
        self.checkBox.setText(_translate("LinearInterpolationDialogBase", "Taking into account impassibility?", None))
        self.label.setText(_translate("LinearInterpolationDialogBase", "Start node cost:", None))
        self.label_2.setText(_translate("LinearInterpolationDialogBase", "End node cost:", None))
        self.label_3.setText(_translate("LinearInterpolationDialogBase", "Flow direction:", None))
        self.label_4.setText(_translate("LinearInterpolationDialogBase", "Side of diffusion:", None))
        self.label_5.setText(_translate("LinearInterpolationDialogBase", "Impassability:", None))
        self.label_6.setText(_translate("LinearInterpolationDialogBase", "Pixel nb (X):", None))
        self.lineEdit_5.setText(_translate("LinearInterpolationDialogBase", "500", None))
        self.label_7.setText(_translate("LinearInterpolationDialogBase", "Pixel nb (Y):", None))
        self.label_8.setText(_translate("LinearInterpolationDialogBase", "Pixel size (X):", None))
        self.label_9.setText(_translate("LinearInterpolationDialogBase", "Pixel size(Y):", None))
        self.label_10.setText(_translate("LinearInterpolationDialogBase", "Search radius:", None))
        self.checkBox_2.setText(_translate("LinearInterpolationDialogBase", "Add raster to current map?", None))
        self.label_11.setText(_translate("LinearInterpolationDialogBase", "Diffusion speed:", None))
        self.lineEdit_6.setText(_translate("LinearInterpolationDialogBase", "4", None))
        self.label_12.setText(_translate("LinearInterpolationDialogBase", "Variable diffusion speed:", None))
        self.label_13.setText(_translate("LinearInterpolationDialogBase", "From start to end", None))
        self.label_14.setText(_translate("LinearInterpolationDialogBase", "From end to start", None))
        self.label_15.setText(_translate("LinearInterpolationDialogBase", "Decimals:", None))
        self.lineEdit_7.setText(_translate("LinearInterpolationDialogBase", "5", None))
        self.pushButton.setText(_translate("LinearInterpolationDialogBase", "Save raster as...", None))

